/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.greve.View;

import com.greve.Controller.Controller;
import com.greve.Model.Address;
import com.greve.Model.Donor;

import javax.swing.*;
import java.text.NumberFormat;

/**
 *
 * @author Paulo-PC
 */
public class Frame_Cad_Donor extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Cad_Donor
     */
    public Frame_Cad_Donor(int id) {
        initComponents();

        if(Controller.logged == 1){
            btnOk.setEnabled(false);
            btnDeletar.setEnabled(false);
        }

        if(id != 0){
            preencheTela(id);
        }

    }

    private void maskFormatter(){
        try {

            if (cbbTipo.getSelectedIndex() == 0) {
                javax.swing.text.MaskFormatter cpfCnpj = new javax.swing.text.MaskFormatter("###.###.###-##");
                txtCpfCnpj = new javax.swing.JFormattedTextField(cpfCnpj);
            } else {
                javax.swing.text.MaskFormatter cpfCnpj = new javax.swing.text.MaskFormatter("##.###.###/####-##");
                txtCpfCnpj = new javax.swing.JFormattedTextField(cpfCnpj);
            }

            javax.swing.text.MaskFormatter numero = new javax.swing.text.MaskFormatter("####");
            txtNumero = new javax.swing.JFormattedTextField(numero);

            javax.swing.text.MaskFormatter contato = new javax.swing.text.MaskFormatter("(##) # ####-####");
            txtContato = new javax.swing.JFormattedTextField(contato);

            javax.swing.text.MaskFormatter cep = new javax.swing.text.MaskFormatter("#####-###");
            txtCEP = new javax.swing.JFormattedTextField(cep);

        }catch (Exception ignored){

        }
    }

    private void preencheTela(int id) {
        int idAddress = 0;
        Donor donor = Controller.getDonorById(id);

        if(donor != null){
            idAddress = donor.getIdAddress();
        }

        Address ad = Controller.getAddressById(idAddress);

        if(donor != null && ad != null) {
            txtId.setText(String.valueOf(donor.getId()));
            txtNome.setText(donor.getfirstName());
            txtSobrenome.setText(donor.getLastName());
            txtCpfCnpj.setText(donor.getCpfCnpj());
            txtEmail.setText(donor.getEmail());
            txtContato.setText(donor.getContact());
            cbbTipo.setSelectedIndex(donor.getType());

            txtRua.setText(ad.getRua());
            txtNumero.setText(ad.getNumero());
            txtBairro.setText(ad.getBairro());
            txtCEP.setText(ad.getCep());
            cbbTipoEndereco.setSelectedIndex(ad.getType());
            txtComplemento.setText(ad.getComplemento());

        } else {
            int input = JOptionPane.showConfirmDialog(null,"Deseja cadastrar novo Doador?",
                    "Novo Cadastro", JOptionPane.YES_NO_OPTION);

            if(input == 0){
                txtId.setEnabled(false);
            }

            limpaTela();
        }
    }

    public void limpaTela(){
        txtId.setText("");
        txtNome.setText("");
        txtSobrenome.setText("");
        txtCpfCnpj.setText("");
        txtEmail.setText("");
        txtContato.setText("");
        txtRua.setText("");
        txtBairro.setText("");
        txtNumero.setText("");
        txtCEP.setText("");
        txtComplemento.setText("");
        cbbTipo.setSelectedIndex(0);
        cbbTipoEndereco.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCpfCnpj = new javax.swing.JFormattedTextField(NumberFormat.getInstance());
        txtContato = new javax.swing.JFormattedTextField(NumberFormat.getInstance());
        txtId = new javax.swing.JFormattedTextField(NumberFormat.getInstance());
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbbTipoEndereco = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        txtCEP = new javax.swing.JFormattedTextField(NumberFormat.getInstance());
        txtNumero = new javax.swing.JFormattedTextField(NumberFormat.getInstance());
        jPanel6 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Nome:");

        txtNome.setSelectionColor(new java.awt.Color(255, 153, 0));

        jLabel1.setText("Sobrenome:");

        txtSobrenome.setSelectionColor(new java.awt.Color(255, 153, 0));

        jLabel2.setText("Tipo:");

        cbbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fisica", "Juridica" }));

        jLabel3.setText("CPF/CNPJ:");

        jLabel4.setText("Email:");

        txtEmail.setSelectionColor(new java.awt.Color(255, 153, 0));

        jLabel5.setText("Contato:");

        jLabel13.setText("ID:");

        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addComponent(jLabel1)
                        .addComponent(txtSobrenome)
                        .addComponent(jLabel2)
                        .addComponent(cbbTipo, 0, 255, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtEmail)
                        .addComponent(jLabel5)
                        .addComponent(txtNome)
                        .addComponent(jLabel13)
                        .addComponent(txtCpfCnpj)
                        .addComponent(txtContato))
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContato, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Rua:");

        txtRua.setSelectionColor(new java.awt.Color(255, 153, 0));

        jLabel7.setText("Bairro:");

        txtBairro.setSelectionColor(new java.awt.Color(255, 153, 0));

        jLabel8.setText("Numero:");

        jLabel10.setText("CEP:");

        jLabel11.setText("Tipo:");

        cbbTipoEndereco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento" }));

        jLabel12.setText("Complemento:");

        txtComplemento.setSelectionColor(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8)
                        .addComponent(jLabel6)
                        .addComponent(txtRua)
                        .addComponent(jLabel7)
                        .addComponent(txtBairro)
                        .addComponent(jLabel11)
                        .addComponent(cbbTipoEndereco, 0, 255, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addComponent(txtComplemento))
                    .addComponent(jLabel10)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnOk.setBackground(new java.awt.Color(255, 255, 255));
        btnOk.setText("1");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("4");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("3");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("2");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeletar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if(!txtNome.getText().trim().equals("") ||
                !txtSobrenome.getText().trim().equals("") ||
                !txtCpfCnpj.getText().trim().equals("") ||
                !txtEmail.getText().trim().equals("") ||
                !txtContato.getText().trim().equals("") ||
                !txtRua.getText().trim().equals("") ||
                !txtBairro.getText().trim().equals("") ||
                !txtNumero.getText().trim().equals("") ||
                !txtCEP.getText().trim().equals("") ||
                !txtComplemento.getText().trim().equals("") ||
                !txtId.getText().trim().equals("") ||
                !txtId.isEnabled())
        {
            limpaTela();

            if(!txtId.isEnabled()){
                txtId.setEnabled(true);
            }
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        int id = 0;
        int idAddress = 0;

        if(!txtNome.getText().trim().equals("") ||
                !txtSobrenome.getText().trim().equals("") ||
                !txtCpfCnpj.getText().trim().equals("") ||
                !txtEmail.getText().trim().equals("") ||
                !txtContato.getText().trim().equals("") ||
                !txtRua.getText().trim().equals("") ||
                !txtBairro.getText().trim().equals("") ||
                !txtNumero.getText().trim().equals("") ||
                !txtCEP.getText().trim().equals("") ||
                !txtComplemento.getText().trim().equals(""))
        {

            String nome = txtNome.getText();
            String sobrenome = txtSobrenome.getText();
            String cpfCnpj = txtCpfCnpj.getText();
            String email = txtEmail.getText();
            String contato = txtContato.getText();
            int tipo = cbbTipo.getSelectedIndex();

            String rua = txtRua.getText();
            String bairro = txtBairro.getText();
            String numero = txtNumero.getText();
            String cep = txtCEP.getText();
            String complemento = txtComplemento.getText();
            int tipoEndereco = cbbTipoEndereco.getSelectedIndex();

            if (txtId.getText().trim().equals("")) {
                idAddress = Controller.createAddress(rua, bairro, numero, cep, complemento, tipoEndereco);
                id = Controller.createDonor(nome, sobrenome, cpfCnpj, email, contato, tipo, idAddress);

                if(idAddress > 0 && id > 0){
                    txtId.setText(String.valueOf(id));
                    JOptionPane.showMessageDialog(null, "Cadastro OK!");

                    if(!txtId.isEnabled()){
                        txtId.setEnabled(true);
                    }
                }
            } else {
                id = Integer.parseInt(txtId.getText());
                idAddress = Controller.updateDonorById(id , nome, sobrenome, cpfCnpj, email, contato, tipo);

                boolean result = Controller.updateAddressById(idAddress, rua, bairro, numero, cep, complemento, tipoEndereco);

                if(result){
                    JOptionPane.showMessageDialog(null, "Cadastro atualizado!");
                }
            }
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:
        if(Controller.logged == 3) {
            int input = JOptionPane.showConfirmDialog(null, "Deseja deletar o doador?", "Deletar...", JOptionPane.YES_NO_OPTION);

            if (input == 0) {
                int id = Integer.parseInt(txtId.getText());

                if (Controller.deleteDonorById(id)) {
                    JOptionPane.showMessageDialog(null, "Doador deletado com sucesso!");
                    limpaTela();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao deletar doador!");
                }
            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        JFrame cons = new Frame_Consulta_Donor(1);
        cons.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        // TODO add your handling code here:
        if(!txtId.getText().trim().equals("")){
            preencheTela(Integer.parseInt(txtId.getText()));
        }
    }//GEN-LAST:event_txtIdFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Cad_Donor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frame_Cad_Donor(0).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> cbbTipo;
    private javax.swing.JComboBox<String> cbbTipoEndereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtContato;
    private javax.swing.JFormattedTextField txtCpfCnpj;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JTextField txtRua;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables
}
